name: Update OpenTabletDriver

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install Flatpak and Flatpak-Builder
        run: |
          sudo add-apt-repository ppa:flatpak/stable -y
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder

      - name: Set up Flathub remote
        run: |
          flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  
      - name: Install SDKs and Runtime
        run: |
          flatpak install flathub org.freedesktop.Platform//23.08 -y
          flatpak install flathub org.freedesktop.Sdk//23.08 -y
          flatpak install flathub org.freedesktop.Sdk.Extension.dotnet6//23.08 -y
          
      - name: Download OpenTabletDriver latest release
        run: |
          curl -s https://api.github.com/repos/OpenTabletDriver/OpenTabletDriver/releases/latest \
          | grep "browser_download_url.*zip" \
          | cut -d '"' -f 4 \
          | wget -i -
          
      - name: Download flatpak-dotnet-generator.py script
        run: wget https://raw.githubusercontent.com/flatpak/flatpak-builder-tools/master/dotnet/flatpak-dotnet-generator.py
      
      - name: Generate linux-x64.json
        run: python flatpak-dotnet-generator.py linux-x64.json ./OpenTabletDriver.UX.Gtk/OpenTabletDriver.UX.Gtk.csproj --runtime linux-x64 --freedesktop 23.08
      
      - name: Generate linux-arm64.json
        run: python flatpak-dotnet-generator.py linux-arm64.json ./OpenTabletDriver.UX.Gtk/OpenTabletDriver.UX.Gtk.csproj --runtime linux-arm64 --freedesktop 23.08
      
      - name: Replace json files
        run: |
          mv linux-x64.json ./sources/linux-x64.json
          mv linux-arm64.json ./sources/linux-arm64.json
      
      - name: Create new branch
        run: |
          NEW_BRANCH="auto-update-$(date +'%Y%m%d%H%M%S')"
          git checkout -b $NEW_BRANCH
      
      - name: Modify net.opentabletdriver.OpenTabletDriver.yaml
        run: |
          TAG=$(curl -s https://api.github.com/repos/OpenTabletDriver/OpenTabletDriver/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
          sed -i "s/tag: .*/tag: $TAG/" net.opentabletdriver.OpenTabletDriver.yaml
          echo "# Generated by GitHub Actions. $(date -u +'%Y-%m-%d %H:%M:%S %Z')" >> net.opentabletdriver.OpenTabletDriver.yaml
      
      - name: Commit changes
        run: |
          git add .
          git commit -m "Update OpenTabletDriver"
      
      - name: Push changes
        run: |
          git push --set-upstream origin $NEW_BRANCH
      
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "${{ github.head_ref }}"
          destination_branch: "master"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Update OpenTabletDriver to latest version"
          pr_body: "This PR updates the OpenTabletDriver configurations to the latest version."
