name: Update

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      FREEDESKTOP_VERSION: "24.08"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Flatpak and Flatpak-Builder
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder

      - name: Set up Flathub remote
        run: flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

      - name: Install SDKs and Runtime
        run: |
          flatpak install flathub org.freedesktop.Platform//${{ env.FREEDESKTOP_VERSION }} -y
          flatpak install flathub org.freedesktop.Sdk//${{ env.FREEDESKTOP_VERSION }} -y
          flatpak install flathub org.freedesktop.Sdk.Extension.dotnet8//${{ env.FREEDESKTOP_VERSION }} -y

      - name: Download and extract OpenTabletDriver latest release
        run: |
          TAG=$(curl -s https://api.github.com/repos/OpenTabletDriver/OpenTabletDriver/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
          URL="https://github.com/OpenTabletDriver/OpenTabletDriver/archive/refs/tags/${TAG}.tar.gz"
          curl -L $URL -o ${{ github.workspace }}/OpenTabletDriver-${TAG}.tar.gz
          mkdir ${{ github.workspace }}/temp
          tar -xzf OpenTabletDriver-${TAG}.tar.gz -C ${{ github.workspace }}/temp

      - name: Download flatpak-dotnet-generator.py script
        run: wget https://raw.githubusercontent.com/first-storm/flatpak-builder-tools/7719d451c3ded70f658385f6471d5deb42952be2/dotnet/flatpak-dotnet-generator.py

      - name: Generate JSONs for different architectures and move them
        run: |
          SUBDIR=$(basename $(find ${{ github.workspace }}/temp -mindepth 1 -maxdepth 1 -type d))
          CS_PROJ_PATH="${{ github.workspace }}/temp/${SUBDIR}/OpenTabletDriver.UX.Gtk/OpenTabletDriver.UX.Gtk.csproj"
          python flatpak-dotnet-generator.py linux-x64.json $CS_PROJ_PATH --runtime linux-x64 --freedesktop ${{ env.FREEDESKTOP_VERSION }}
          python flatpak-dotnet-generator.py linux-arm64.json $CS_PROJ_PATH --runtime linux-arm64 --freedesktop ${{ env.FREEDESKTOP_VERSION }}
          mv linux-x64.json ${{ github.workspace }}/sources/linux-x64.json
          mv linux-arm64.json ${{ github.workspace }}/sources/linux-arm64.json

      - name: Retrieve and Update OpenTabletDriver Tag in YAML Precisely
        run: |
          # Retrieve the latest tag
          TAG=$(curl -s https://api.github.com/repos/OpenTabletDriver/OpenTabletDriver/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
          
          # Use awk to update the tag in a more controlled manner
          awk -v tag="$TAG" '
          BEGIN {p=0}
          /- name: opentabletdriver/ {p=1}
          p==1 && /tag:/ {print "        tag: "tag; p=0; next}
          {print}
          ' net.opentabletdriver.OpenTabletDriver.yaml > temp.yaml && mv temp.yaml net.opentabletdriver.OpenTabletDriver.yaml
          echo "# Generated by GitHub Actions. $(date -u +'%Y-%m-%d %H:%M:%S %Z')" >> ${{ github.workspace }}/net.opentabletdriver.OpenTabletDriver.yaml

      - name: Cleanup
        run: rm -rf ${{ github.workspace }}/temp ${{ github.workspace }}/*.tar.gz ${{ github.workspace }}/flatpak-dotnet-generator.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: OpenTabletDriver-Files
          path: |
            ${{ github.workspace }}/sources/linux-x64.json
            ${{ github.workspace }}/sources/linux-arm64.json
            ${{ github.workspace }}/net.opentabletdriver.OpenTabletDriver.yaml

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "Update OpenTabletDriver configurations"
          title: "Automated OpenTabletDriver Update"
          body: "This is an auto-generated PR with the latest OpenTabletDriver configurations."
          branch: "feature/update-opentabletdriver"
          base: "master"
          delete-branch: true
