name: Update

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      FREEDESKTOP_VERSION: "23.08"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install Flatpak and Flatpak-Builder
        run: |
          sudo add-apt-repository ppa:flatpak/stable -y
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder

      - name: Set up Flathub remote
        run: flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  
      - name: Install SDKs and Runtime
        run: |
          flatpak install flathub org.freedesktop.Platform//${{ env.FREEDESKTOP_VERSION }} -y
          flatpak install flathub org.freedesktop.Sdk//${{ env.FREEDESKTOP_VERSION }} -y
          flatpak install flathub org.freedesktop.Sdk.Extension.dotnet6//${{ env.FREEDESKTOP_VERSION }} -y
          
      - name: Download and extract OpenTabletDriver latest release
        run: |
          TAG=$(curl -s https://api.github.com/repos/OpenTabletDriver/OpenTabletDriver/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
          URL="https://github.com/OpenTabletDriver/OpenTabletDriver/archive/refs/tags/${TAG}.tar.gz"
          curl -L $URL -o OpenTabletDriver-${TAG}.tar.gz
          mkdir ${{ github.workspace }}/temp
          tar -xzf OpenTabletDriver-${TAG}.tar.gz -C ${{ github.workspace }}/temp
          
      - name: Download flatpak-dotnet-generator.py script
        run: wget https://raw.githubusercontent.com/flatpak/flatpak-builder-tools/master/dotnet/flatpak-dotnet-generator.py
      
      - name: Generate linux-x64.json and linux-arm64.json
        run: |
          python flatpak-dotnet-generator.py linux-x64.json ${{ github.workspace }}/temp/OpenTabletDriver.UX.Gtk/OpenTabletDriver.UX.Gtk.csproj --runtime linux-x64 --freedesktop ${{ env.FREEDESKTOP_VERSION }}
          python flatpak-dotnet-generator.py linux-arm64.json ${{ github.workspace }}/temp/OpenTabletDriver.UX.Gtk/OpenTabletDriver.UX.Gtk.csproj --runtime linux-arm64 --freedesktop ${{ env.FREEDESKTOP_VERSION }}
      
      - name: Replace json files
        run: |
          mv linux-x64.json ${{ github.workspace }}/sources/linux-x64.json
          mv linux-arm64.json ${{ github.workspace }}/sources/linux-arm64.json
      
      - name: Modify net.opentabletdriver.OpenTabletDriver.yaml
        run: |
          sed -i "s/tag: .*/tag: $TAG/" ${{ github.workspace }}/net.opentabletdriver.OpenTabletDriver.yaml
          echo "# Generated by GitHub Actions. $(date -u +'%Y-%m-%d %H:%M:%S %Z')" >> ${{ github.workspace }}/net.opentabletdriver.OpenTabletDriver.yaml
      
      - name: Cleanup
        run: |
          rm -rf ${{ github.workspace }}/temp flatpak-dotnet-generator.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: OpenTabletDriver-Files
          path: |
            ${{ github.workspace }}/sources/linux-x64.json
            ${{ github.workspace }}/sources/linux-arm64.json
            ${{ github.workspace }}/net.opentabletdriver.OpenTabletDriver.yaml

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "Update OpenTabletDriver configurations"
          title: "Automated OpenTabletDriver Update"
          body: "This is an auto-generated PR with the latest OpenTabletDriver configurations."
          branch: "feature/update-opentabletdriver"
          base: "master"
          delete-branch: true
